apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamon-backend
  labels:
    app: teamon
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teamon
      tier: backend
  template:
    metadata:
      labels:
        app: teamon
        tier: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-org/teamon-backend:latest
        ports:
        - containerPort: 7000
        env:
        - name: ENV_FILE
          value: .env.prod
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: teamon-backend
spec:
  selector:
    app: teamon
    tier: backend
  ports:
  - port: 7000
    targetPort: 7000
  type: ClusterIP 